set_property -dict { PACKAGE_PIN J15 IOSTANDARD LVCMOS33 } [get_ports a]  
set_property -dict { PACKAGE_PIN L16 IOSTANDARD LVCMOS33 } [get_ports b]  
set_property -dict { PACKAGE_PIN M13 IOSTANDARD LVCMOS33 } [get_ports c]  
set_property -dict { PACKAGE_PIN H17 IOSTANDARD LVCMOS33 } [get_ports y]  
set_property -dict { PACKAGE_PIN N14 IOSTANDARD LVCMOS33 } [get_ports x]